# This is a basic workflow to help you get started with Actions

name: Linux Image Build Arm32

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACTION_TOKEN }}

      - name: "Install toolchain On Linux"
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y gperf help2man libtool-bin libncurses5-dev

      - name: "Install toolchain On macOS"
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install autoconf automake bash binutils gawk gnu-sed \
          gnu-tar help2man ncurses

      - name: "Install Crosstool"
        run: |
          wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf.tar.xz
          sudo tar -vxf gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf.tar.xz -C /usr/share/
          sudo ln -s /usr/share/gcc-arm-10.2-2020.11-x86_64-arm-none-linux-gnueabihf/bin/* /usr/bin/
          wget https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu.tar.xz
          sudo tar -vxf gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu.tar.xz -C /usr/share/
          sudo ln -s /usr/share/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu/bin/* /usr/bin/

      - name: checkout branch
        run: |
          git checkout master
          git submodule foreach 'git checkout master'

      - name: build kernel
        run: |
          export BR_KERNEL=https://github.com/mengdemao/kernel.git
          export BR_KERNEL_VERSION=v2.0
          ./build.sh all
